server:
  port: 9000

keycloak:
  base-url: http://localhost:8080/auth
  realm: demo
  realm-url: ${keycloack.base-url}/realms/${keycloack.realm}

spring:
  security:
    user:
      name: user
      password: pass
