server:
  port: 9000

keycloak:
  base-url: http://localhost:8080/auth
  realm: demo
  realm-url: ${keycloack.base-url}/realms/${keycloack.realm}

spring:
  security:
    user:
      name: admin
      password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/spass_db_dev
    username: admin
    password: pass
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5





# PostgreSQL
